/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package e.metnum;

/**
 *
 * @author Rey
 */
public class METODOSMC extends javax.swing.JFrame {

    /**
     * Creates new form METODOSMC
     */
    public METODOSMC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton18 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(65, 105, 225));
        jPanel1.setPreferredSize(new java.awt.Dimension(975, 400));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jButton1.setText("METODO 1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 87, 101, 55));

        jButton2.setText("METODO 2");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 87, 101, 55));

        jButton3.setText("METODO 3");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 87, 100, 55));

        jButton4.setText("METODO 4");
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 87, 101, 55));

        jButton5.setText("METODO 4");
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 147, 101, 55));

        jButton6.setText("METODO 6");
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 147, 101, 55));

        jButton7.setText("METODO 7");
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 147, 100, 55));

        jButton8.setText("METODO 8");
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 147, 101, 55));

        jButton9.setText("METODO 9");
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 207, 101, 55));

        jButton10.setText("METODO 10");
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 207, 101, 55));

        jButton11.setText("METODO 11");
        jPanel1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 207, 100, 55));

        jButton12.setText("METODO 12");
        jPanel1.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 207, 101, 55));

        jButton13.setText("METODO 13");
        jPanel1.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 267, 101, 55));

        jButton14.setText("METODO 14");
        jPanel1.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 267, 101, 55));

        jButton15.setText("METODO 15");
        jPanel1.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 267, 100, 55));

        jButton16.setText("METODO 16");
        jPanel1.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 267, 101, 55));

        jLabel1.setFont(new java.awt.Font("Yu Gothic Light", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("METODOS MC");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 11, 280, -1));

        jButton17.setText("Regresar");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 37, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 0, 0));

        jLabel2.setText("jLabel2");

        jButton18.setText("jButton18");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton18)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton18))
                .addGap(18, 18, 18))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 146, 66));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 975, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
 Principal pp = new Principal();
        pp.setVisible(true);
        this.dispose();        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       //BOTON METODO 1
       jButton2.setVisible(false);
         jButton3.setVisible(false);
           jButton4.setVisible(false);
             jButton5.setVisible(false);
               jButton6.setVisible(false);
                 jButton7.setVisible(false);
                   jButton8.setVisible(false);
                     jButton9.setVisible(false);
                      jButton10.setVisible(false);
                        jButton11.setVisible(false);
                          jButton12.setVisible(false);
                            jButton13.setVisible(false);
                              jButton14.setVisible(false);
                                jButton15.setVisible(false);
                                  jButton16.setVisible(false);
                                    jPanel2.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

     private void jButton18MouseClicked(java.awt.event.MouseEvent evt) {                                       
     jPanel2.setVisible(true);
      jButton2.setVisible(true);
         jButton3.setVisible(true);
           jButton4.setVisible(true);
             jButton5.setVisible(true);
               jButton6.setVisible(true);
                jButton7.setVisible(true);
         jButton8.setVisible(true);
           jButton9.setVisible(true);
             jButton10.setVisible(true);
               jButton11.setVisible(true);
                jButton12.setVisible(true);
         jButton13.setVisible(true);
           jButton14.setVisible(true);
             jButton15.setVisible(true);
               jButton16.setVisible(true);
                 jButton18.setVisible(true);
           
               jButton1.setVisible(true);
               jPanel2.setVisible(false);
    }                                     
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jButton18.setVisible(false);
        jPanel2.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(METODOSMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(METODOSMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(METODOSMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(METODOSMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new METODOSMC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
