/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package e.metnum;

/**
 *
 * @author bigpo
 */
public class QuizOR extends javax.swing.JFrame {

    /**
     * Creates new form QuizOR
     */
    public QuizOR() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton16 = new javax.swing.JRadioButton();
        jRadioButton17 = new javax.swing.JRadioButton();
        jRadioButton18 = new javax.swing.JRadioButton();
        jRadioButton19 = new javax.swing.JRadioButton();
        jRadioButton20 = new javax.swing.JRadioButton();
        jRadioButton21 = new javax.swing.JRadioButton();
        jRadioButton22 = new javax.swing.JRadioButton();
        jRadioButton23 = new javax.swing.JRadioButton();
        jRadioButton24 = new javax.swing.JRadioButton();
        jRadioButton28 = new javax.swing.JRadioButton();
        jRadioButton29 = new javax.swing.JRadioButton();
        jRadioButton30 = new javax.swing.JRadioButton();
        jRadioButton31 = new javax.swing.JRadioButton();
        jRadioButton32 = new javax.swing.JRadioButton();
        jRadioButton33 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jRadioButton34 = new javax.swing.JRadioButton();
        jRadioButton35 = new javax.swing.JRadioButton();
        jRadioButton36 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jRadioButton37 = new javax.swing.JRadioButton();
        jRadioButton38 = new javax.swing.JRadioButton();
        jRadioButton39 = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jRadioButton40 = new javax.swing.JRadioButton();
        jRadioButton41 = new javax.swing.JRadioButton();
        jRadioButton42 = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        jRadioButton43 = new javax.swing.JRadioButton();
        jRadioButton44 = new javax.swing.JRadioButton();
        jRadioButton45 = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        jRadioButton46 = new javax.swing.JRadioButton();
        jRadioButton47 = new javax.swing.JRadioButton();
        jRadioButton48 = new javax.swing.JRadioButton();

        jLabel10.setText("jLabel10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jRadioButton5.setText("a)I=0.142416952");
        jPanel1.add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, -1, -1));

        jRadioButton6.setText("b)I=0.1666324891");
        jPanel1.add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 530, 120, -1));

        jRadioButton7.setText("a)2.705508427");
        jPanel1.add(jRadioButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        jRadioButton8.setText("b)3.652232561");
        jPanel1.add(jRadioButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, -1, -1));

        jRadioButton9.setText("c)8.662244090");
        jPanel1.add(jRadioButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, -1, -1));

        jRadioButton10.setText("c)I=0.139335619");
        jPanel1.add(jRadioButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 530, -1, -1));

        jRadioButton11.setText("a)I=0.14189715 ");
        jPanel1.add(jRadioButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 970, -1, -1));

        jRadioButton12.setText("c)I=0.17526612");
        jPanel1.add(jRadioButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 970, -1, -1));

        jRadioButton15.setText("b)I=0.16841132");
        jPanel1.add(jRadioButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 970, -1, -1));

        jRadioButton16.setText("a)I=-27");
        jPanel1.add(jRadioButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 760, -1, -1));

        jRadioButton17.setText("b)=-40");
        jPanel1.add(jRadioButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 760, -1, -1));

        jRadioButton18.setText("c)Ninguna");
        jPanel1.add(jRadioButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 760, -1, -1));

        jRadioButton19.setText("a)I=0.921683");
        jPanel1.add(jRadioButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 1180, -1, -1));

        jRadioButton20.setText("c)I=0.3216411622");
        jPanel1.add(jRadioButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 1180, -1, -1));

        jRadioButton21.setText("b)I=0.575583627");
        jPanel1.add(jRadioButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 1180, -1, -1));

        jRadioButton22.setText("a)0.0132");
        jPanel1.add(jRadioButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1400, -1, -1));

        jRadioButton23.setText("c) 0.1092");
        jPanel1.add(jRadioButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 1400, -1, -1));

        jRadioButton24.setText("b)0.5670");
        jPanel1.add(jRadioButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 1400, -1, -1));

        jRadioButton28.setText("a)1673.972");
        jPanel1.add(jRadioButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 1620, -1, -1));

        jRadioButton29.setText("c)1636.3216");
        jPanel1.add(jRadioButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1620, -1, -1));

        jRadioButton30.setText("b)1655.9671");
        jPanel1.add(jRadioButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 1620, -1, -1));

        jRadioButton31.setText("a)0.782");
        jPanel1.add(jRadioButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1830, -1, -1));

        jRadioButton32.setText("c)0.939");
        jPanel1.add(jRadioButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 1830, -1, -1));

        jRadioButton33.setText("b)0.6531");
        jPanel1.add(jRadioButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 1830, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/metnum/LineaRecta.PNG"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 280, 290));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\bigpo\\OneDrive\\escritorio\\ReglaTrapezoideal.PNG")); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 250, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\bigpo\\OneDrive\\escritorio\\newtoncotasabiertas.PNG")); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\bigpo\\OneDrive\\escritorio\\1terciode3simpson.PNG")); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 790, 250, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/metnum/3octovossimpson.PNG"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1010, 250, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/metnum/EULER.PNG"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1220, 250, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\bigpo\\OneDrive\\escritorio\\eulerhaciaatras.PNG")); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1430, 260, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\bigpo\\OneDrive\\escritorio\\rungekuttacorrecto.PNG")); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1860, 250, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\bigpo\\OneDrive\\escritorio\\eulermodificado.PNG")); // NOI18N
        jLabel9.setText("jLabel8");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1650, 250, -1));

        jRadioButton34.setText("a)k1=-0.6");
        jPanel1.add(jRadioButton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 2040, -1, -1));

        jRadioButton35.setText("c)y1=0.651632664");
        jPanel1.add(jRadioButton35, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 2040, -1, -1));

        jRadioButton36.setText("b)k2=0.282154221");
        jPanel1.add(jRadioButton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 2040, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\bigpo\\OneDrive\\escritorio\\metodorange3erorden.PNG")); // NOI18N
        jLabel11.setText("jLabel8");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 2080, 250, -1));

        jRadioButton37.setText("a)k2=0.25666617218");
        jPanel1.add(jRadioButton37, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 2260, 100, -1));

        jRadioButton38.setText("c)k2=0.5677777777");
        jPanel1.add(jRadioButton38, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 2260, 110, -1));

        jRadioButton39.setText("b)k2=0.25793981");
        jPanel1.add(jRadioButton39, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 2260, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\bigpo\\OneDrive\\escritorio\\Rangekutta4toorden.PNG")); // NOI18N
        jLabel12.setText("jLabel8");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 2320, 250, -1));

        jRadioButton40.setText("a)y1=0.537781321");
        jPanel1.add(jRadioButton40, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 2500, 100, -1));

        jRadioButton41.setText("c)y1=0.52612190");
        jPanel1.add(jRadioButton41, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 2500, 110, -1));

        jRadioButton42.setText("b)y1=0.511617621");
        jPanel1.add(jRadioButton42, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 2500, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/metnum/38derugensimpson.PNG"))); // NOI18N
        jLabel13.setText("jLabel8");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 2540, 250, -1));

        jRadioButton43.setText("a)k3=-0.428060426");
        jPanel1.add(jRadioButton43, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 2720, 100, -1));

        jRadioButton44.setText("c)k3=-0.2261352817.");
        jPanel1.add(jRadioButton44, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 2720, 100, -1));

        jRadioButton45.setText("b)k3=-0.459012562");
        jPanel1.add(jRadioButton45, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 2720, 100, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\bigpo\\OneDrive\\escritorio\\ORDENSUPERIOR.PNG")); // NOI18N
        jLabel14.setText("jLabel8");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 2740, 250, 180));

        jRadioButton46.setText("a)m1=-0.30");
        jRadioButton46.setToolTipText("");
        jPanel1.add(jRadioButton46, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 2920, 100, -1));

        jRadioButton47.setText("c)m1=-0.22");
        jPanel1.add(jRadioButton47, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 2920, 100, -1));

        jRadioButton48.setText("b)m1=-0.55");
        jPanel1.add(jRadioButton48, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 2920, 100, -1));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 2956, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuizOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuizOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuizOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuizOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuizOR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton17;
    private javax.swing.JRadioButton jRadioButton18;
    private javax.swing.JRadioButton jRadioButton19;
    private javax.swing.JRadioButton jRadioButton20;
    private javax.swing.JRadioButton jRadioButton21;
    private javax.swing.JRadioButton jRadioButton22;
    private javax.swing.JRadioButton jRadioButton23;
    private javax.swing.JRadioButton jRadioButton24;
    private javax.swing.JRadioButton jRadioButton28;
    private javax.swing.JRadioButton jRadioButton29;
    private javax.swing.JRadioButton jRadioButton30;
    private javax.swing.JRadioButton jRadioButton31;
    private javax.swing.JRadioButton jRadioButton32;
    private javax.swing.JRadioButton jRadioButton33;
    private javax.swing.JRadioButton jRadioButton34;
    private javax.swing.JRadioButton jRadioButton35;
    private javax.swing.JRadioButton jRadioButton36;
    private javax.swing.JRadioButton jRadioButton37;
    private javax.swing.JRadioButton jRadioButton38;
    private javax.swing.JRadioButton jRadioButton39;
    private javax.swing.JRadioButton jRadioButton40;
    private javax.swing.JRadioButton jRadioButton41;
    private javax.swing.JRadioButton jRadioButton42;
    private javax.swing.JRadioButton jRadioButton43;
    private javax.swing.JRadioButton jRadioButton44;
    private javax.swing.JRadioButton jRadioButton45;
    private javax.swing.JRadioButton jRadioButton46;
    private javax.swing.JRadioButton jRadioButton47;
    private javax.swing.JRadioButton jRadioButton48;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
